V-3: made the component structure
conho-web/stage-3 pull request #2
Opened 2022-08-08 16:40 UTC by conho-web

2022-08-08 19:13 UTC, i-barysiuk requested changes
В целом по Vue замечаний нет копоненты классные именованы правильно, но есть вопросики к гуд практис по верстке. Наверное я должен был сказать тебе это все на этапе ревью прошлой таске, но как-то проглядел, ничего сейчас наверстаем)

2022-08-08 19:13 UTC, i-barysiuk commented on src/components/ToDo.vue
> +    <div :class="$style.wrapper">
Зачем тебе две обертки?

2022-08-08 19:13 UTC, i-barysiuk commented on src/components/ToDo.vue
>    border: 2px solid #ffca93;
В цветах удобно использовать scss переменные

2022-08-08 19:13 UTC, i-barysiuk commented on src/components/atoms/AddButton.vue
> +  background-image: url("data:image/svg+xml,%3csvg width='100%25' height='100%25' xmlns='http://www.w3.org/2000/svg'%3e%3crect width='100%25' height='100%25' fill='none' rx='10' ry='10' stroke='%23FF
Использовать svg в виде бэкграунда не очень популярная практика, ты уверен что без него нельзя обойтись?

2022-08-08 19:13 UTC, i-barysiuk commented on src/components/atoms/AddButton.vue
> +  color: #ffca93;
Цвета в переменные

2022-08-08 19:13 UTC, i-barysiuk commented on src/components/atoms/AddButton.vue
> +}
scss поддерживает вложенность 
удобнее читать 
.add{
   &:hover{
      color: ...
   }
}

2022-08-08 19:13 UTC, i-barysiuk commented on src/components/atoms/TabButton.vue
> +  <button :class="[$style.showButton, $style.showAll]">
style showAll не используется

2022-08-08 19:13 UTC, i-barysiuk commented on src/components/atoms/TabButton.vue
> +    {{ title }}
Наверное удобнее слот в этом случае

2022-08-08 19:13 UTC, i-barysiuk commented on src/components/organisms/Title.vue
> +    <h1 :class="$style.h1">to do list</h1>
если именовать классы как теги то позже можно запутаться обращаешься ли ты к тегу или к классу, а если потом класс применить на тег h2 то получится тег h2 c классом h1 - это ведь вообще анархия)

2022-08-09 09:10 UTC, conho-web commented on src/components/ToDo.vue
> +    <div :class="$style.wrapper">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/98264524/183610783-ba178519-44e7-4b14-959c-b429af75aef7.png">
wrapper - обертка для блока
а todo - секция, в которой задаю background и высоту 100vh

2022-08-09 09:27 UTC, conho-web commented on src/components/atoms/AddButton.vue
> +  background-image: url("data:image/svg+xml,%3csvg width='100%25' height='100%25' xmlns='http://www.w3.org/2000/svg'%3e%3crect width='100%25' height='100%25' fill='none' rx='10' ry='10' stroke='%23FF
В css вроде как нельзя регулировать ширину этих линий
Можно просто border сделать, но линии будут не как в макете

2022-08-09 12:16 UTC, merged